<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => '',
    'page_home_bck' => '',
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_about' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
  ),
);


/* Auto generated by Themes Administration on : 2014.05.01 04:22:38 */
